services:
  django:
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - default
    build:
      context: .
    working_dir: /matematics
    command: sh -c "python manage.py makemigrations && python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
  db:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_DB=matematics
      - POSTGRES_USER=matematics
      - POSTGRES_PASSWORD=matematics
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matematics -d matematics"]
      interval: 5s
      timeout: 5s
      retries: 10
  celery:
    build: .
    working_dir: /matematics
    command: sh -c "celery -A matematics worker --loglevel=info"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DJANGO_SETTINGS_MODULE=matematics.settings
      - DATABASE_URL=postgres://matematics:matematics@db:5432/matematics
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//

networks:
  default:
    driver: bridge

