# Generated by Django 5.1.6 on 2025-03-03 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PhotoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='images/users_answers')),
            ],
            options={
                'verbose_name': 'фото/файл',
                'verbose_name_plural': 'фаото/файлы',
            },
        ),
        migrations.CreateModel(
            name='SolvedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('first_part_exist', models.BooleanField(default=False)),
                ('first_part_score', models.IntegerField(default=0)),
                ('first_part_max_score', models.IntegerField(default=0)),
                ('second_part_exist', models.BooleanField(default=False)),
                ('second_part_score', models.IntegerField(default=0)),
                ('second_part_max_score', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_text', models.TextField(max_length=1000)),
                ('second_text', models.TextField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('solution_image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('solution', models.TextField(max_length=1000)),
                ('answer', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('right_solved', models.IntegerField(default=0)),
                ('solved_count', models.IntegerField(default=0)),
                ('solved_percent', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('max_score', models.IntegerField()),
                ('name', models.TextField(max_length=100, unique=True)),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Номер задачи',
                'verbose_name_plural': 'Номера задач',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SolvedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gived_answer', models.CharField(max_length=20, null=True)),
                ('score', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('images', models.ManyToManyField(to='main.photofile')),
            ],
            options={
                'verbose_name': 'Решенная задача',
                'verbose_name_plural': 'Решенные задачи',
            },
        ),
    ]
