# Generated by Django 5.1.6 on 2025-03-03 17:39

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedtest',
            name='solved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_solved_tests', to=settings.AUTH_USER_MODEL, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='solvedtest',
            name='users_answers',
            field=models.ManyToManyField(to='main.solvedtask'),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.category'),
        ),
        migrations.AddField(
            model_name='solvedtask',
            name='main_task_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_tasks', to='main.task'),
        ),
        migrations.AddField(
            model_name='test',
            name='tasks',
            field=models.ManyToManyField(to='main.task'),
        ),
        migrations.AddField(
            model_name='solvedtest',
            name='main_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_tests', to='main.test'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['number'], name='main_topic_number_50c3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['created'], name='main_topic_created_d987f3_idx'),
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.topic'),
        ),
        migrations.AddField(
            model_name='category',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.topic'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['id'], name='main_task_id_4038fb_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category'], name='main_task_categor_2d79d5_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created'], name='main_task_created_85a5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='main_catego_name_5111b9_idx'),
        ),
    ]
