# Generated by Django 5.1.6 on 2025-03-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_test_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(default='in_progress'),
        ),
        migrations.AlterField(
            model_name='task',
            name='first_text',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='task',
            name='second_text',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
