# Generated by Django 5.1.6 on 2025-03-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(default='in_progress', max_length=50),
        ),
    ]
