# Generated by Django 5.1.6 on 2025-03-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
    ]
