# Generated by Django 5.1.6 on 2025-03-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_test_created_by'),
        ('users', '0002_user_favorites_tasks_user_favorites_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites_tasks',
            field=models.ManyToManyField(to='main.task'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorites_tests',
            field=models.ManyToManyField(to='main.test'),
        ),
    ]
