# Generated by Django 5.1.6 on 2025-03-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_test_name_alter_test_status'),
        ('users', '0003_user_favorites_tasks_user_favorites_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites_tasks',
            field=models.ManyToManyField(blank=True, to='main.task'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites_tests',
            field=models.ManyToManyField(blank=True, to='main.test'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Мужской', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(default='Ученик', max_length=50),
        ),
    ]
