# Generated by Django 5.1.6 on 2025-03-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_favorites_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_proof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_number',
            field=models.CharField(default=123, max_length=300),
            preserve_default=False,
        ),
    ]
