# Generated by Django 5.1.6 on 2025-03-17 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_email_proof_user_verification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='set_pass_link_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 22, 56, 39, 950277)),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_number',
            field=models.CharField(max_length=1000),
        ),
    ]
