# Generated by Django 5.1.6 on 2025-03-17 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_set_pass_link_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='set_pass_link_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 23, 2, 51, 752604)),
        ),
    ]
