# Generated by Django 5.1.6 on 2025-03-17 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_verification_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_number',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='set_pass_link_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 23, 5, 7, 317924)),
        ),
    ]
