# Generated by Django 5.1.6 on 2025-03-17 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_verification_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_number',
            new_name='verification_token',
        ),
        migrations.AlterField(
            model_name='user',
            name='set_pass_link_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 23, 7, 26, 739138)),
        ),
    ]
