# Generated by Django 5.1.6 on 2025-03-17 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_verification_number_user_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='set_pass_link_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 23, 7, 33, 303166)),
        ),
    ]
