# Generated by Django 5.1.6 on 2025-03-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_set_pass_link_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='set_pass_link_created',
            field=models.CharField(default=1742242890.3122635),
        ),
    ]
